#!/usr/bin/env bash

# cargo size --release --bin msc
# cargo bloat --release --bin msc
cargo build --release --bin msc

arm-none-eabi-size target/thumbv7m-none-eabi/release/msc | tail -n 1 >> size.txt

cat size.txt
