#!/usr/bin/env bash

if ! hash tmux 2>/dev/null; then
	echo "Install tmux first..."
	exit 1
fi

function has-session {
	tmux has-session -t $1 2>/dev/null
}

function get-shell {
	getent passwd $USER | awk -F: '{ print $7 }'
}

if [ "$1" == "kill" ]; then
	echo "Killing tmux"
	tmux kill-server
	exit 0
fi


SESSION_NAME="zcssr"
SHELL="`get-shell`"
echo $SHELL
if has-session $SESSION_NAME ; then
	echo "Session $SESSION_NAME already exists"
else
        echo "Creating new session $SESSION_NAME"
        tmux new-session -d -s $SESSION_NAME -n $SESSION_NAME
        tmux split-window -h
        tmux select-pane -t 0
        tmux split-window -h
        tmux select-pane -t 0
        tmux split-window -v -p 20
        tmux select-pane -t 2
        tmux split-window -v -p 20
        tmux select-pane -t 4

        #+-----------------------+
        #| watch | spare | shell |
        #| zcssr |       |       |
        #|-------|-------|       |
        #| watch | open  |       |
        #|  itm  | ocd   |       |
        #+-----------------------+

        tmux send-keys -t $SESSION_NAME.0 ./watch Enter

        tmux send-keys -t $SESSION_NAME.1 ./monitor_itm Enter
        tmux send-keys -t $SESSION_NAME.1 ./watch Enter

        tmux send-keys -t $SESSION_NAME.3 ./run_openocd Enter
fi 

tmux attach-session -d -t $SESSION_NAME
